### ISSUE TITLE
Remove default page opening.

### ISSUE THREAD

**Issue by motleydev** [zeke/jus#22]
Great tool so far! I would personally like to see the default opening of the URL removed. That being said, I want that removed because it's a nuisance to integrate with my live-reload tool of choice so it's possibly when you incorporate a live-reload solution that will resolve my issues all-together! See my comments on the live-reload topic for my preferred tool of choice!

**Comment by zeke** [comment]
Good call. I made a quick attempt at getting a live reload setup working, but I got stuck and aborted the effort. Feel free to work on this if you like, or I will give it another try when I have time.

What tool(s) do you use for live reloading?

**Comment by zeke** [comment]
Landed in 0.18.1
