### ISSUE TITLE
Use `404`.html` if avilable for custom 404 page

### ISSUE THREAD

**Issue by cvan** [zeke/jus#37]
Could do what GitHub Pages and Surge do: use a `404.html` file in the project root, if available.

**Comment by zeke** [comment]
Just to clarify, do you mean adding a step to the build process that writes a default `/404.html` if one does not exist?

**Comment by cvan** [comment]
No, I mean if a user has a `404.html` in the project root, use that instead of [this line](https://github.com/zeke/jus/blob/0441a9a/lib/routes.js#L40).

**Comment by zeke** [comment]
Great idea! I don't have time to work on this right away, but would happily merge and release a pull request if you're up for it.

**Comment by elingerojo** [comment]
I am interested to work on it but need some feedback.
What about auto generating a plain vanilla 404 page if there is none already?

It could be placed in a auto generated folder. For the names of the 404 file and folder, we can use a configuration file like the ` redirects.json `

Maybe could be a good idea to autogenerate ` jussettings.json ` in liu of the ` redirects.json ` and include the redirects in it.

The ` jussettings.json `  will be created only if there is none. This way, the user could edit it to fit.

...and if present, **jus** can use the information in it to name 404 file and/or folder, etc.

Other approach could be to have a settings folder with ` redirect.json ` and other settings files.

Any ideas to keep the jus configuration simplicity?

**Comment by cvan** [comment]
I've been following [Surge.sh's `ROUTER` format](https://surge.sh/help/adding-redirects). See this project, [`yonder`](https://github.com/sintaxi/yonder/pull/5/files) (which Surge uses).

**Comment by elingerojo** [comment]
Surge.sh's ROUTER format looks good. It's clean and simple. And easy for the front-end developer to deduct how it works. I like it.

Project `yonder` make me rethink about the original objective of the 404 page.

1. I could include  some yonder code in the future but not as this issue solution but as a part of a solution for Routing (server-side like and client-side using [Navigo](http://krasimirtsonev.com/blog/article/deep-dive-into-client-side-routing-navigo-pushstate-hash) or [director](https://github.com/flatiron/director). This will be another issue. And certainly could use the Surge.sh's ROUTER format.
2. I realize, at present, that the 404 custom page is for the front-end **Developer**, not for the **User** that visit the static web site. **Sorry, my bad**.

Any server-side Routing solution will add some amount of obstructive configuration. And any client-side Routing will add obstructive boilerplate.

Now I understand the original @cvan proposal that solves the issue.
> No, I mean if a user has a 404.html in the project root, use that instead of [this line](https://github.com/zeke/jus/blob/0441a9a/lib/routes.js#L40).

... and do not break the `Jus `promise:
> Jus ...for making static websites with no configuration and no boilerplate code.

The decision on how to serve a 404 page to be seen by the **User** who visits the web site should be left to the Developer.

...so this 404 solution should be just a visual appealing help on the developing stage.

I opened a custom-404 branch and it's ready to PR

**Comment by zeke** [comment]
Hey sorry for the delay responding; I'm offline for the week. I will take a look at all this in detail and get back to you next week.
