### ISSUE TITLE
Don't try to parse `svg` fonts as images

### ISSUE THREAD

**Issue by jdormit** [zeke/jus#48]
If you have an SVG font in your static site, Jus will try to pass it through `image-size` during the transpilation process. This throws an error, since SVG fonts don't have `width`, `height`, or `viewbox` attributes.

One solution could be parsing SVGs for the `<font>` tag, and not passing them through `image-size` if that's the case.

**Comment by zeke** [comment]
Derp. Been thinking about remove the magical image features entirely. They slow the whole thing down and make the dependency tree much bigger. Are you by chance using that image metadata at all?

**Comment by jdormit** [comment]
Nope, not at all! I added [this](https://github.com/jdormit/jus/commit/4197687cc11626797cd5dd21db1a54e49a4204be) really simple change in my fork - basically just check for `</font>` in SVG files. Want me to do a pull request, or would a different solution be better?

**Comment by zeke** [comment]
A PR for that would be great! I can ship a new release right away, and address the larger "support image metadata or not" down the line...

**Comment by zeke** [comment]
Fixed by #49 👍
